/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: v5.26.2.10099
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFormatBulkResource {
    #[serde(rename = "ids", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ids: Option<Option<Vec<i32>>>,
    #[serde(rename = "includeCustomFormatWhenRenaming", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub include_custom_format_when_renaming: Option<Option<bool>>,
}

impl CustomFormatBulkResource {
    pub fn new() -> CustomFormatBulkResource {
        CustomFormatBulkResource {
            ids: None,
            include_custom_format_when_renaming: None,
        }
    }
}

