/*
 * Radarr
 *
 * Radarr API docs
 *
 * The version of the OpenAPI document: v5.26.2.10099
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RatingChild {
    #[serde(rename = "votes", skip_serializing_if = "Option::is_none")]
    pub votes: Option<i32>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<f64>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<models::RatingType>,
}

impl RatingChild {
    pub fn new() -> RatingChild {
        RatingChild {
            votes: None,
            value: None,
            r#type: None,
        }
    }
}

